organism: Anthophora plagiata
assembly:
  name: iyAntPlag1
  displayName: A. plagiata genome assembly GCA_963995485.1
  accession: GCA_963995485.1
  url: ftp://ftp.ebi.ac.uk/pub/databases/ena/wgs/public/cax/CAXEFL01.fasta.gz
  fileName: CAXEFL01.fasta.gz
  defaultScaffold: "ENA|CAXEFL010000280|CAXEFL010000280.1"
tracks:
- name: Protein-coding genes
  url: https://nextcloud.dc.scilifelab.se/s/CcnntPSTKqXMzLk/download/GCA_963995485.1_iyAntPlag1_genomic.gff.renamed.gff.gz
- name: Repeats
  url: "https://nextcloud.dc.scilifelab.se/s/XDCDXCwi8BsSMoe/download/Anthophora_plagiata_repeats.gff" #temp storage for the track
  fileName: "Anthophora_plagiata_repeats.gff"
  defaultSession: true 
- name: Transcripts (Isoseq)
  url: "https://nextcloud.dc.scilifelab.se/s/5MBS8ZeBfQkSbPx/download/Anthophora_plagiata_isoseq.gff" #temp storage for the track
  fileName: "Anthophora_plagiata_isoseq.gff" 
  defaultSession: true
- name: "Nucleotide diversity (Pi), 5kb windows"
  url: "https://nextcloud.dc.scilifelab.se/s/Z527RkCJbtcaj6J/download/plag_5kb.windowed.pi" #temp storage for the track
  fileName: "plag_5kb.windowed.bed"
  addTrack: false
  defaultSession: true
  GWAS: true
  scoreColumnGWAS: "PI"
  color: "rgb(242, 142, 44)"
- name: "Tajima's D, calculated with 10kb windows"
  url: "https://nextcloud.dc.scilifelab.se/s/RinRnGCoYnHW3FZ/download/plagiata.Tajima.D.end_column_5kb_midpoint.bed" #temp storage for the track
  fileName: "plagiata.Tajima.D.end_column_5kb_midpoint.bed"
  addTrack: false
  defaultSession: true
  GWAS: true
  scoreColumnGWAS: "TajimaD"


