organism: Anthophora quadrimaculata
assembly:
  name: iyAntQuad1
  displayName: A. quadrimaculata genome assembly GCA_963995475.1
  accession: GCA_963995475.1
  url: ftp://ftp.ebi.ac.uk/pub/databases/ena/wgs/public/cax/CAXEFK01.fasta.gz
  fileName: CAXEFK01.fasta.gz
tracks:
- name: Protein-coding genes
  url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/963/995/475/GCA_963995475.1_iyAntQuad1/GCA_963995475.1_iyAntQuad1_genomic.gff.gz
- name: Repeats
  url: "https://figshare.scilifelab.se/ndownloader/files/60419360"
  fileName: "Anthophora_quadrimaculata_repeats.gff"
  defaultSession: true 
- name: Transcripts (Isoseq)
  url: "https://figshare.scilifelab.se/ndownloader/files/60419357"
  fileName: "Anthophora_quadrimaculata_isoseq.gff"
  defaultSession: true
- name: "Nucleotide diversity (Pi), 5kb windows"
  url: "https://figshare.scilifelab.se/ndownloader/files/60419342"
  fileName: "quad_5kb.windowed.bed"
  addTrack: false
  defaultSession: true
  GWAS: true
  scoreColumnGWAS: "PI"
  color: "rgb(242, 142, 44)"
- name: "Tajima's D, calculated with 10kb windows"
  url: "https://figshare.scilifelab.se/ndownloader/files/60419339"
  fileName: "quadri.Tajima.D.end_column_5kb_midpoint.bed"
  addTrack: false
  defaultSession: true
  GWAS: true
  scoreColumnGWAS: "TajimaD"
